name: Nexus Mining

on:
  workflow_dispatch:

jobs:
  mining:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 hours maximum

    steps:
      - name: Initial Setup
        id: setup
        run: |
          # Set strict error handling
          set -euo pipefail
          
          # Create timestamp
          TIMESTAMP=$(date -u '+%Y%m%d_%H%M%S')
          echo "timestamp=$TIMESTAMP" >> $GITHUB_OUTPUT
          
          # Create directory structure with error checking
          MINING_HOME="$HOME/mining_operation_${TIMESTAMP}"
          mkdir -p "$MINING_HOME"/{logs,scripts,data,backup}
          mkdir -p "$MINING_HOME/logs"/{system,process,errors,performance}
          
          # Verify directories were created
          if [ ! -d "$MINING_HOME" ]; then
            echo "Failed to create directory structure"
            exit 1
          fi
          
          # Export paths
          {
            echo "MINING_HOME=$MINING_HOME"
            echo "LOG_PATH=$MINING_HOME/logs"
            echo "TIMESTAMP=$TIMESTAMP"
          } >> $GITHUB_ENV
          
          # Save session info
          cat << EOF > "$MINING_HOME/session_info.json"
          {
            "workflow_id": "${{ github.run_id }}",
            "repository": "${{ github.repository }}",
            "user": "${{ github.actor }}",
            "start_time": "$(date -u '+%Y-%m-%d %H:%M:%S')",
            "runner": "${{ runner.os }}-${{ runner.arch }}"
          }
          EOF
          
          echo "Initial setup completed successfully"
        shell: bash

      - name: System Optimization
        id: optimize
        run: |
          # Error handling
          set -euo pipefail
          
          {
            echo "=== System Optimization Started at $(date -u '+%Y-%m-%d %H:%M:%S UTC') ==="
            
            # Function for error handling
            handle_error() {
              echo "Error on line $1"
              exit 1
            }
            trap 'handle_error $LINENO' ERR
            
            # Stop unnecessary services
            echo "Stopping non-essential services..."
            for service in snapd unattended-upgrades apache2 mysql docker; do
              sudo systemctl stop $service 2>/dev/null || true
            done
            
            # CPU Optimization
            echo "Optimizing CPU settings..."
            for cpu in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do
              echo "performance" | sudo tee "$cpu" >/dev/null || true
            done
            
            # System tuning
            echo "Tuning system parameters..."
            sudo sysctl -w vm.swappiness=10
            sudo sysctl -w kernel.sched_min_granularity_ns=10000000
            sudo sysctl -w vm.dirty_ratio=60
            
            echo "=== System Optimization Completed at $(date -u '+%Y-%m-%d %H:%M:%S UTC') ==="
          } 2>&1 | tee "$LOG_PATH/system/optimization.log"
        shell: bash

      - name: Install Dependencies
        id: dependencies
        run: |
          # Error handling
          set -euo pipefail
          
          {
            echo "=== Installing Dependencies at $(date -u '+%Y-%m-%d %H:%M:%S UTC') ==="
            
            # Update package lists with retry
            for i in {1..3}; do
              if sudo apt-get update; then
                break
              fi
              echo "Retry $i: Failed to update package lists"
              sleep 5
            done
            
            # Required packages
            PACKAGES=(
              expect
              curl
              htop
              sysstat
              numactl
              net-tools
              tree
              jq
              iotop
              python3
              python3-pip
            )
            
            # Install packages with error handling
            for package in "${PACKAGES[@]}"; do
              echo "Installing $package..."
              if ! sudo apt-get install -y "$package"; then
                echo "Failed to install $package"
                exit 1
              fi
            done
            
            echo "=== Dependencies Installation Completed at $(date -u '+%Y-%m-%d %H:%M:%S UTC') ==="
          } 2>&1 | tee "$LOG_PATH/system/dependencies.log"
        shell: bash

      - name: Create Monitoring Scripts
        id: monitoring
        run: |
          # Error handling
          set -euo pipefail
          
          # Create monitoring script
          cat << 'EOF' > "$MINING_HOME/scripts/monitor.sh"
          #!/bin/bash
          set -euo pipefail
          
          LOG_DIR="$1"
          INTERVAL=60
          
          while true; do
            TIMESTAMP=$(date -u '+%Y-%m-%d_%H:%M:%S')
            
            # System metrics
            {
              echo "=== System Metrics at $TIMESTAMP ==="
              echo "--- CPU Usage ---"
              top -bn1 | head -n 20
              echo "--- Memory Usage ---"
              free -h
              echo "--- Disk Usage ---"
              df -h
              echo "--- Network Stats ---"
              netstat -s | head -n 20
              echo "--- Process Stats ---"
              ps aux --sort=-%cpu | head -n 10
            } > "$LOG_DIR/performance/metrics_${TIMESTAMP}.log"
            
            # Process monitoring
            if pgrep -f nexus-network > /dev/null; then
              {
                echo "=== Nexus Process Stats at $TIMESTAMP ==="
                ps aux | grep nexus-network
                echo "--- Process Tree ---"
                pstree -p "$(pgrep -f nexus-network)"
              } > "$LOG_DIR/process/nexus_${TIMESTAMP}.log"
            fi
            
            sleep "$INTERVAL"
          done
          EOF
          
          chmod +x "$MINING_HOME/scripts/monitor.sh"
          
          echo "Monitoring scripts created successfully"
        shell: bash

      - name: Run Nexus Mining Operation
        id: mining
        run: |
          # Error handling
          set -euo pipefail
          
          {
            echo "=== Starting Mining Operation at $(date -u '+%Y-%m-%d %H:%M:%S UTC') ==="
            
            # Start monitoring
            "$MINING_HOME/scripts/monitor.sh" "$LOG_PATH" &
            MONITOR_PID=$!
            
            # Download Nexus CLI with retry
            MAX_RETRIES=5
            for ((i=1; i<=MAX_RETRIES; i++)); do
              echo "Downloading Nexus CLI (attempt $i/$MAX_RETRIES)..."
              if curl -sSL --retry 3 --retry-delay 10 https://cli.nexus.xyz/ | sh; then
                echo "Download successful"
                break
              fi
              if [ $i -eq $MAX_RETRIES ]; then
                echo "Failed to download after $MAX_RETRIES attempts"
                exit 1
              fi
              sleep 10
            done
            
            NEXUS_HOME="$HOME/.nexus"
            BIN_DIR="$NEXUS_HOME/bin"
            
            # Function to start node
            start_node() {
              echo "Starting Nexus node at $(date -u '+%Y-%m-%d %H:%M:%S UTC')..."
              sudo numactl --physcpubind=0-3 --membind=0 expect -c "
                log_user 1
                spawn $BIN_DIR/nexus-network start --node-id 36659912
                expect {
                  \"Do you agree to the Nexus Beta Terms of Use?\" {
                    send \"Y\r\"
                    exp_continue
                  }
                  timeout {
                    exit 1
                  }
                  eof {
                    exit 0
                  }
                }
              " 2>&1 | tee -a "$LOG_PATH/process/node.log" &
              echo $!
            }
            
            # Start initial node
            NODE_PID=$(start_node)
            echo "Node started with PID: $NODE_PID"
            
            # Optimize process priority
            sudo renice -n -20 -p $NODE_PID || true
            sudo chrt -f -p 99 $NODE_PID || true
            
            # Monitor loop
            RESTART_COUNT=0
            MAX_RESTARTS=5
            END_TIME=$((SECONDS + 21300))  # 5h 55m (buffer for 6h limit)
            
            while [ $SECONDS -lt $END_TIME ]; do
              if ! ps -p $NODE_PID > /dev/null 2>&1; then
                echo "Node process died at $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
                RESTART_COUNT=$((RESTART_COUNT + 1))
                
                if [ $RESTART_COUNT -gt $MAX_RESTARTS ]; then
                  echo "Maximum restart attempts ($MAX_RESTARTS) reached"
                  break
                fi
                
                NODE_PID=$(start_node)
                echo "Node restarted with PID: $NODE_PID"
                sleep 60
              fi
              
              echo "[$(date -u '+%Y-%m-%d %H:%M:%S UTC')] Runtime: ${SECONDS}s, Restarts: $RESTART_COUNT" >> "$LOG_PATH/process/status.log"
              sleep 30
            done
            
            # Cleanup
            echo "Stopping monitoring process..."
            kill $MONITOR_PID || true
            echo "Stopping node process..."
            pkill -f nexus-network || true
            
            echo "=== Mining Operation Completed at $(date -u '+%Y-%m-%d %H:%M:%S UTC') ==="
          } 2>&1 | tee "$LOG_PATH/process/mining_operation.log"
        shell: bash

      - name: Collect and Package Logs
        if: always()
        id: collect_logs
        run: |
          # Error handling
          set -euo pipefail
          
          {
            echo "=== Collecting Logs at $(date -u '+%Y-%m-%d %H:%M:%S UTC') ==="
            
            # Create summary report
            cat << 'EOF' > "$MINING_HOME/summary.md"
            # Mining Operation Summary
            
            ## Session Information
            - Workflow ID: ${{ github.run_id }}
            - Repository: ${{ github.repository }}
            - User: ${{ github.actor }}
            - Start Time: $(jq -r .start_time "$MINING_HOME/session_info.json")
            - End Time: $(date -u '+%Y-%m-%d %H:%M:%S')
            
            ## System Configuration
            - Runner: ${{ runner.os }}-${{ runner.arch }}
            - CPU Configuration: Performance mode
            - Process Priority: -20 (highest)
            
            ## Directory Structure
            \`\`\`
            $(tree "$MINING_HOME" || echo "Tree command failed")
            \`\`\`
            EOF
            
            # Create archive
            cd "$HOME"
            ARCHIVE_NAME="mining_logs_${TIMESTAMP}.tar.gz"
            
            echo "Creating log archive..."
            if tar -czf "$ARCHIVE_NAME" "mining_operation_${TIMESTAMP}/"; then
              echo "Log archive created successfully"
              ls -lh "$ARCHIVE_NAME"
            else
              echo "Failed to create main archive, creating empty fallback..."
              tar -czf "$ARCHIVE_NAME" -T /dev/null
            fi
            
            echo "=== Log Collection Completed at $(date -u '+%Y-%m-%d %H:%M:%S UTC') ==="
          } 2>&1 | tee -a "$LOG_PATH/system/log_collection.log"
        shell: bash

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mining-logs-${{ github.run_id }}-${{ env.TIMESTAMP }}
          path: ~/mining_logs_${{ env.TIMESTAMP }}.tar.gz
          retention-days: 7
          compression-level: 9
