name: Nexus Mining

on:
  workflow_dispatch:

jobs:
  mining:
    runs-on: ubuntu-latest
    timeout-minutes: 360 # 6 hours
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y expect curl

      - name: Run Nexus Mining CLI
        run: |
          set +e
          echo "Downloading Nexus CLI..."
          curl -sSL --retry 3 --retry-delay 10 https://cli.nexus.xyz/ | sh
          sleep 30 # wait for the CLI to install
          echo "Nexus CLI downloaded successfully!"
          NEXUS_HOME="$HOME/.nexus"
          BIN_DIR="$NEXUS_HOME/bin"
          echo "Starting Nexus node..."
          expect -c "spawn $BIN_DIR/nexus-network start --node-id 798900; expect { \"Do you agree to the Nexus Beta Terms of Use?\" { send \"Y\r\"; exp_continue } eof { exit 0 } };"
          echo "Nexus node started successfully!"
        continue-on-error: true
        shell: bash

      - name: Keep mining for 6 hours
        run: |
          sleep 6h
          echo "6 hours have passed, stopping Nexus node..."
        shell: bash

      - name: Cleanup
        run: |
          pkill -f nexus-network
          echo "Nexus node stopped successfully!"
        continue-on-error: true
        shell: bash

      - name: Logs
        run: |
          echo "Displaying Nexus node logs..."
          cat ~/.nexus/nexus-node.log
        continue-on-error: true
        shell: bash
