# ... previous steps remain the same ...

      - name: Collect and Package Logs
        if: always()
        run: |
          # Ensure we're in the right directory
          cd $HOME
          
          # Verify log directory exists
          if [ ! -d "mining_logs" ]; then
            echo "Creating mining_logs directory"
            mkdir -p mining_logs
          fi
          
          # Create a basic log if none exists
          if [ -z "$(ls -A mining_logs)" ]; then
            echo "Creating basic log file"
            echo "Workflow ID: ${{ github.run_id }}" > mining_logs/basic.log
            echo "Timestamp: $(date -u)" >> mining_logs/basic.log
          fi
          
          # Create tar file with explicit path
          tar -czf mining_logs.tar.gz mining_logs/
          
          # Verify tar file was created
          if [ -f mining_logs.tar.gz ]; then
            echo "Log archive created successfully"
            ls -lh mining_logs.tar.gz
          else
            echo "Failed to create log archive"
            exit 1
          fi

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mining-logs-${{ github.run_id }}
          path: ~/mining_logs.tar.gz  # Simplified path
          retention-days: 7
          compression-level: 9
